# Generated by Django 3.0 on 2020-05-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200522_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttoimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='commenttovideo',
            name='file',
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_eighth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_fifth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_first',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_fourth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_ninth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_second',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_seventh',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_sixth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttoimage',
            name='file_third',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_image/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_eighth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_fifth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_first',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_fourth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_ninth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_second',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_seventh',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_sixth',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
        migrations.AddField(
            model_name='commenttovideo',
            name='file_third',
            field=models.FileField(blank=True, null=True, upload_to='comment_to_video/'),
        ),
    ]
