# Generated by Django 3.0 on 2020-05-22 18:03

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('profile', models.ImageField(blank=True, upload_to='profile_images/', verbose_name='profile')),
                ('last_online', models.DateTimeField(default=datetime.datetime(2020, 5, 22, 18, 3, 22, 399748, tzinfo=utc))),
                ('friends', models.ManyToManyField(default='', related_name='_account_friends_+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('images', models.ManyToManyField(to='files.Image')),
                ('music_playlist', models.ManyToManyField(to='files.Playlist')),
                ('user_permissions', models.ManyToManyField(to='auth.Permission')),
                ('videos', models.ManyToManyField(to='files.Video')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
