# Generated by Django 3.0 on 2020-05-22 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usrauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 22, 39, 55, 325796, tzinfo=utc)),
        ),
    ]
