# Generated by Django 3.0 on 2020-05-22 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200522_2239'),
        ('usrauth', '0002_auto_20200522_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='files.Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 22, 44, 44, 380494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='music_playlist',
            field=models.ManyToManyField(blank=True, null=True, to='files.Playlist'),
        ),
        migrations.AlterField(
            model_name='account',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='files.Video'),
        ),
    ]
