# Generated by Django 3.0 on 2020-05-22 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usrauth', '0006_auto_20200522_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 23, 15, 27, 985121, tzinfo=utc)),
        ),
    ]
