# Generated by Django 3.0 on 2020-06-01 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usrauth', '0007_auto_20200522_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 58, 28, 848371, tzinfo=utc)),
        ),
    ]
